server:
  port: 8886


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dilshag/Smart_Parking_Management_System
          default-label: main
          username: dilshag


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/